### ISSUE TITLE
Release new maven version

### ISSUE THREAD

**Issue by magicDGS** [quarkiverse/quarkus-jdbc-sqlite#172]
Hello, I have realized that this project has no new version since a while and I am wondering if it will be possible to release a new version that contains the fixes made in https://github.com/quarkiverse/quarkus-jdbc-sqlite/pull/156. I am using this library and it took a while to find a way to remove the warning, so I want to use the latest version and also upgrade sqlite from xerial that is also not up-to-date in the latest maven version.

@alexeysharandin - please, I will really appreciate if it is possible to do this as soon as you have some time. Thanks!

**Comment by alexeysharandin** [comment]
Hi @magicDGS, version 3.0.10 released with latest changes

**Comment by magicDGS** [comment]
Thanks @alexeysharandin
