### ISSUE TITLE
error when creating unique constraint

### ISSUE THREAD

**Issue by davinwang** [quarkiverse/quarkus-jdbc-sqlite#93]
error happens when declaring a unique constraint:
```
    @Column(name = "uk_column", unique = true)
    public String uk_column;
```
It reports
```
Error` executing `DDL` "alter table dt_table add constraint UKjlid30ljaxbdig1jijlrcqejh unique (uk_column)" via JDBC [[SQLITE_ERROR]
```
The right DDL should be 
```
   create unique constraint UKjlid30ljaxbdig1jijlrcqejh on dt_table(uk_column)
```

**Comment by alexeysharandin** [comment]
Hi, looks like problem in [Community Dialect](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java) and need to open issue for Hibernate Team.
